name: Makefile CI

on:
  push:
    branches: [ master, ocheretenko, Julia, Misha ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: make
      
    - name: Run tests
      run: make test
      
    - name: Run out/example
      run: make out/example
      
    - name: Clean
      run: make clean
